# -*- coding: utf-8 -*-
"""Predict_func.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zZaoZTttGVIAg-BqWWDhg40cM_pet3P

# Prediction
"""

# from huggingface_hub import notebook_login

# notebook_login()

from transformers import pipeline
classifier = pipeline("sentiment-analysis", model = "mohammad-osoolian/parsbert-finetuned")
# classifier = pipeline("sentiment-analysis", model = "mohammadhabp/finetuned-parsbert-uncased-ArmanEmo")

classifier.predict('حس خیلی خوبی دارم')

classifier.predict('امروز حال من خوب نیست')

classifier.predict('نگرانم برایش اتفاقی افتاده باشد')

def predict(inpath, classifier, outpath=None):
  sentences = []
  with open(inpath, 'r', encoding="utf-8-sig") as f:
    for line in f.readlines():
      sentences.append(line.strip())
  predictions = classifier.predict(sentences)
  if outpath != None:
    with open(outpath, 'w') as f:
      f.write('Label, Score\n')
      for i in range(len(sentences)):
        f.write(f"{predictions[i]['label']}, {predictions[i]['score']}\n")

  return predictions

predict('predict_test.csv', classifier, outpath='results.csv')